meaning_quote = ["Radiate boundless love towards the entire world.",
                "Radiate boundless love towards the entire world.",
                "Give, even if you only have a little.",
                "Conquer anger with non-anger. Conquer badness with goodness. Conquer meanness with generosity. Conquer dishonesty with truth.",
                "Those who cling to perceptions and views wander the world offending people.",
                "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.",
                "I will not look at another's bowl intent on finding fault: a training to be observed.",
                "Let none find fault with others; let none see the omissions and commissions of others. But let one see one’s own acts, done and undone.",
                "Should a person do good, let him do it again and again. Let him find pleasure therein, for blissful is the accumulation of good.",
                "May all beings have happy minds.",
                "Delight in heedfulness! Guard well your thoughts!",
                "Should you find a wise critic to point out your faults, follow him as you would a guide to hidden treasure.",
                "Should a seeker not find a companion who is better or equal, let them resolutely pursue a solitary course.",
                "In whom there is no sympathy for living beings: know him as an outcast.",
                "Hatred is never appeased by hatred in this world. By non-hatred alone is hatred appeased. This is a law eternal.",
                "Live with no sense of 'mine,' not forming attachment to experiences.",
                "Better it is to live one day seeing the rise and fall of things than to live a hundred years without ever seeing the rise and fall of things.",
                "One is not called noble who harms living beings. By not harming living beings one is called noble.",
                "If a man going down into a river, swollen and swiftly flowing, is carried away by the current — how can he help others across?",
                "All conditioned things are impermanent—when one sees this with wisdom, one turns away from suffering.",
                "Ardently do today what must be done. Who knows? Tomorrow, death comes.",
                 "The world is afflicted by death and decay. But the wise do not grieve, having realized the nature of the world."
                ]
